// Generated by CoffeeScript 1.8.0
(function() {
  var Compiler, _;

  _ = require('underscore');

  Compiler = (function() {
    Compiler.prototype.default_options = {};

    function Compiler(options) {
      if (options == null) {
        options = {};
      }
      this.options = _.defaults(options, this.default_options);
    }

    Compiler.prototype.set = function(options) {
      var k, v;
      for (k in options) {
        v = options[k];
        this.options[k] = v;
      }
      return this;
    };

    return Compiler;

  })();

  module.exports = Compiler;

}).call(this);
